import { ShipData, SkinData, RouteData } from "./types";

export const ROUTES_DATA: RouteData[] = [
  {
    id: "route-certification",
    name: "Vôo de Certificação",
    description: "Um tutorial prático com 10 aros. Começa super fácil com aros alinhados e sem obstáculos, ficando um pouco desafiador com curvas e asteroides no fim.",
    image: "/src/assets/images/route_certification_1784637771404.jpg",
    numRings: 10,
    ringSpacing: 4000,
    curveIntensityX: 150,
    curveIntensityY: 100,
    curveFrequencyX: 0.2,
    curveFrequencyY: 0.1,
    randomOffset: 40,
    nebulaCount: 30,
    asteroidDensity: 1.2,
    asteroidVelocity: 0,
    difficulty: "Iniciante",
    totalDistance: 40000,
    ambientColor: "#0f172a",
    hasMovingAsteroids: false,
    trafficShipCount: 0
  },
  {
    id: "route-asteroid-alpha",
    name: "Cinturão de Asteroides Alpha",
    description: "Navegue pelo setor de testes cercado por asteroides flutuantes e luas. Perfeito para calibragem de propulsores.",
    image: "/src/assets/images/route_asteroid_alpha_1784637783080.jpg",
    numRings: 12,
    ringSpacing: 4000,
    curveIntensityX: 250,
    curveIntensityY: 150,
    curveFrequencyX: 0.25,
    curveFrequencyY: 0.15,
    randomOffset: 80,
    nebulaCount: 20,
    asteroidDensity: 2.5,
    asteroidVelocity: 0,
    difficulty: "Iniciante",
    totalDistance: 48000,
    ambientColor: "#f97316",
    hasMovingAsteroids: false,
    trafficShipCount: 2
  },
  {
    id: "route-highway",
    name: "Via Láctea Expressa",
    description: "Uma rodovia interestelar de alta velocidade. Baixa densidade de obstáculos, mas distância extrema.",
    image: "/src/assets/images/route_cosmic_highway_1784637880052.jpg",
    numRings: 20,
    ringSpacing: 8000,
    curveIntensityX: 80,
    curveIntensityY: 80,
    curveFrequencyX: 0.02,
    curveFrequencyY: 0.02,
    randomOffset: 20,
    nebulaCount: 60,
    asteroidDensity: 0.2,
    asteroidVelocity: 0,
    difficulty: "Fácil",
    totalDistance: 160000,
    ambientColor: "#10b981",
    hasMovingAsteroids: false,
    trafficShipCount: 40
  },
  {
    id: "route-orion-nebula",
    name: "Vórtice da Nebulosa de Órion",
    description: "Uma corrida tática através de um labirinto instável de gás superaquecido e poeira cósmica ionizada.",
    image: "/src/assets/images/route_orion_nebula_1784637794168.jpg",
    numRings: 15,
    ringSpacing: 3800,
    curveIntensityX: 550,
    curveIntensityY: 350,
    curveFrequencyX: 0.55,
    curveFrequencyY: 0.45,
    randomOffset: 250,
    nebulaCount: 150,
    asteroidDensity: 0.8,
    asteroidVelocity: 8,
    difficulty: "Médio",
    totalDistance: 57000,
    ambientColor: "#a855f7",
    hasMovingAsteroids: true,
    trafficShipCount: 5
  },
  {
    id: "route-ice-field",
    name: "Campos Glaciais de Europa",
    description: "Navegue por um oceano congelado suspenso no espaço. Milhares de blocos de gelo estáticos bloqueiam o caminho.",
    image: "/src/assets/images/route_ice_field_1784637824487.jpg",
    numRings: 16,
    ringSpacing: 4200,
    curveIntensityX: 250,
    curveIntensityY: 250,
    curveFrequencyX: 0.2,
    curveFrequencyY: 0.2,
    randomOffset: 120,
    nebulaCount: 15,
    asteroidDensity: 12.0,
    asteroidVelocity: 0,
    difficulty: "Médio",
    totalDistance: 67200,
    ambientColor: "#0c4a6e",
    hasMovingAsteroids: false,
    trafficShipCount: 2
  },
  {
    id: "route-void",
    name: "Silêncio do Vazio",
    description: "Um teste de velocidade pura e controle inercial. Sem obstáculos, apenas o vácuo absoluto e curvas extremas.",
    image: "/src/assets/images/route_void_silence_1784637890362.jpg",
    numRings: 20,
    ringSpacing: 6000,
    curveIntensityX: 1800,
    curveIntensityY: 1800,
    curveFrequencyX: 0.18,
    curveFrequencyY: 0.15,
    randomOffset: 1200,
    nebulaCount: 0,
    asteroidDensity: 0,
    asteroidVelocity: 0,
    difficulty: "Médio",
    totalDistance: 120000,
    ambientColor: "#09090b",
    hasMovingAsteroids: false,
    trafficShipCount: 0
  },
  {
    id: "route-saturn-rings",
    name: "Anéis Táticos de Saturno",
    description: "Circuito de precisão máxima situado nas fendas geladas dos icônicos anéis planetários de Saturno.",
    image: "/src/assets/images/route_saturn_rings_1784637851043.jpg",
    numRings: 20,
    ringSpacing: 4500,
    curveIntensityX: 400,
    curveIntensityY: 150,
    curveFrequencyX: 0.2,
    curveFrequencyY: 0.1,
    randomOffset: 100,
    nebulaCount: 10,
    asteroidDensity: 8.0,
    asteroidVelocity: 0,
    difficulty: "Difícil",
    totalDistance: 90000,
    ambientColor: "#3b82f6",
    hasMovingAsteroids: false,
    trafficShipCount: 3
  },
  {
    id: "route-plasma",
    name: "Tormenta Energética",
    description: "Relâmpagos cósmicos e nuvens de plasma ionizado. A visibilidade é baixa e as curvas são fechadas.",
    image: "/src/assets/images/route_plasma_storm_1784637838576.jpg",
    numRings: 16,
    ringSpacing: 3600,
    curveIntensityX: 800,
    curveIntensityY: 800,
    curveFrequencyX: 1.2,
    curveFrequencyY: 1.0,
    randomOffset: 650,
    nebulaCount: 100,
    asteroidDensity: 1.5,
    asteroidVelocity: 30,
    difficulty: "Difícil",
    totalDistance: 57600,
    ambientColor: "#8b5cf6",
    hasMovingAsteroids: true,
    trafficShipCount: 4
  },
  {
    id: "route-supernova",
    name: "Remanescente de Supernova",
    description: "Voe através dos restos incandescentes de uma estrela morta, onde detritos em chamas voam em todas as direções.",
    image: "/src/assets/images/route_supernova_remnant_1784637901998.jpg",
    numRings: 15,
    ringSpacing: 3200,
    curveIntensityX: 850,
    curveIntensityY: 850,
    curveFrequencyX: 0.8,
    curveFrequencyY: 0.8,
    randomOffset: 600,
    nebulaCount: 80,
    asteroidDensity: 4.5,
    asteroidVelocity: 45,
    difficulty: "Elite",
    totalDistance: 48000,
    ambientColor: "#ef4444",
    hasMovingAsteroids: true,
    trafficShipCount: 0
  },
  {
    id: "route-black-hole",
    name: "Horizonte de Eventos",
    description: "A gravidade distorce o espaço-tempo. Curvas impossíveis e uma força invisível puxam sua nave para o abismo.",
    image: "/src/assets/images/route_black_hole_1784637807530.jpg",
    numRings: 18,
    ringSpacing: 3500,
    curveIntensityX: 1200,
    curveIntensityY: 1200,
    curveFrequencyX: 0.05,
    curveFrequencyY: 0.05,
    randomOffset: 600,
    nebulaCount: 40,
    asteroidDensity: 0.5,
    asteroidVelocity: 80,
    difficulty: "Elite",
    totalDistance: 63000,
    ambientColor: "#1e1b4b",
    hasMovingAsteroids: true,
    trafficShipCount: 1,
    gravityWell: true
  },
  {
    id: "route-dyson",
    name: "Sucata de Dyson",
    description: "Os restos de uma megaestrutura antiga. Destroços metálicos densos tornam a navegação um pesadelo de sobrevivência.",
    image: "/src/assets/images/route_dyson_scraps_1784637863436.jpg",
    numRings: 20,
    ringSpacing: 2800,
    curveIntensityX: 300,
    curveIntensityY: 300,
    curveFrequencyX: 0.3,
    curveFrequencyY: 0.3,
    randomOffset: 350,
    nebulaCount: 5,
    asteroidDensity: 15.0,
    asteroidVelocity: 15,
    difficulty: "Sobrevivência",
    totalDistance: 56000,
    ambientColor: "#71717a",
    hasMovingAsteroids: true,
    trafficShipCount: 0
  }
];

export const SHIPS_DATA: ShipData[] = [
  {
    id: "nave-jogador",
    name: "Vanguard Prime",
    modelFile: "/NaveJogador.glb",
    class: "Interceptor",
    description: "The legendary pilot's signature spacecraft. Outfitted with overcharged engine cores and high-output secondary thrusters for extreme maneuverability.",
    velocidade: 97,
    aceleracao: 92,
    turbo: 95,
    energia: 45,
    massa: 15,
    price: 0,
    abilityName: "Overdrive Boost",
    abilityDesc: "Temporarily increases top speed by 40% and grants brief invulnerability phases."
  },
  {
    id: "sparrow-02",
    name: "Swift Wind II",
    modelFile: "/StarSparrow02.glb",
    class: "Recon",
    description: "A lightweight recon vessel engineered for long-range scouting operations. Its sensor suite can map entire sectors within seconds.",
    velocidade: 90,
    aceleracao: 100,
    turbo: 85,
    energia: 48,
    massa: 10,
    price: 2500,
    abilityName: "Sensor Sweep",
    abilityDesc: "Reveals hidden enemy placements and highlights strategic resource nodes on the HUD."
  },
  {
    id: "sparrow-03",
    name: "Shadow Phantom",
    modelFile: "/StarSparrow03.glb",
    class: "Fighter",
    description: "Built using a light-absorbing composite frame, the Shadow Phantom excels at striking from dark sectors before the enemy radar even blinks.",
    velocidade: 83,
    aceleracao: 86,
    turbo: 80,
    energia: 44,
    massa: 25,
    price: 4500,
    abilityName: "Cloak Field",
    abilityDesc: "Renders the ship completely invisible to radar and visual tracking for 8 seconds."
  },
  {
    id: "sparrow-04",
    name: "Star Sparrow IV",
    modelFile: "/StarSparrow04.glb",
    class: "Fighter",
    description: "A versatile, highly reliable general-purpose fighter. Known across the galaxy for its balanced handling and easily upgradable weapon hardpoints.",
    velocidade: 86,
    aceleracao: 84,
    turbo: 82,
    energia: 42,
    massa: 25,
    price: 6000,
    abilityName: "Dual Laser Array",
    abilityDesc: "Overcharges primary lasers, doubling fire rate while halving weapon energy draw."
  },
  {
    id: "sparrow-05",
    name: "Crimson Razor",
    modelFile: "/StarSparrow05.glb",
    class: "Heavy Fighter",
    description: "An aggressive heavy assault craft sporting composite titanium plating and dual plasma injectors that melt enemy shield arrays.",
    velocidade: 80,
    aceleracao: 72,
    turbo: 90,
    energia: 38,
    massa: 40,
    price: 9500,
    abilityName: "Plasma Barrage",
    abilityDesc: "Fires a devastating arc of superheated plasma projectiles that dealing heavy thermal splash damage."
  },
  {
    id: "sparrow-06",
    name: "Aegis Defender",
    modelFile: "/StarSparrow06.glb",
    class: "Fighter",
    description: "Designed as a defensive vanguard, the Aegis is equipped with heavy-duty shield capacitors capable of absorbing multiple direct railgun shots.",
    velocidade: 75,
    aceleracao: 78,
    turbo: 70,
    energia: 52,
    massa: 25,
    price: 13000,
    abilityName: "Aegis Barrier",
    abilityDesc: "Projects a spherical energy barrier that blocks all incoming damage and redirects it into the main battery."
  },
  {
    id: "sparrow-07",
    name: "Eclipse Wraith",
    modelFile: "/StarSparrow07.glb",
    class: "Recon",
    description: "A covert spy craft featuring active noise-reduction engines and heat sinks that make it virtually undetectable in planetary atmospheres.",
    velocidade: 92,
    aceleracao: 98,
    turbo: 88,
    energia: 46,
    massa: 10,
    price: 17500,
    abilityName: "Decoy Spark",
    abilityDesc: "Ejects a holographic decoy that draws enemy missile lock-ons away from the ship."
  },
  {
    id: "sparrow-08",
    name: "Titan Behemoth",
    modelFile: "/StarSparrow08.glb",
    class: "Heavy Fighter",
    description: "A massive, brick-solid armored assault vessel. It trades high-speed turns for devastating dual-linked autocannons that tear through capital hulls.",
    velocidade: 65,
    aceleracao: 52,
    turbo: 72,
    energia: 58,
    massa: 40,
    price: 22000,
    abilityName: "Flak Wall",
    abilityDesc: "Deploys a cloud of proximity-detonating micro-explosives, wiping out smaller hostile drones."
  },
  {
    id: "sparrow-09",
    name: "Zephyr Ghost",
    modelFile: "/StarSparrow09.glb",
    class: "Interceptor",
    description: "The fastest model in its class. Built around an experimental fusion drive, the Zephyr is capable of sub-light speeds that defy inertia.",
    velocidade: 100,
    aceleracao: 95,
    turbo: 100,
    energia: 42,
    massa: 15,
    price: 28000,
    abilityName: "Micro-Warp",
    abilityDesc: "Instantly teleports the ship 500 meters forward in its current vector to evade obstacles."
  },
  {
    id: "sparrow-10",
    name: "Hyperion Knight",
    modelFile: "/StarSparrow10.glb",
    class: "Fighter",
    description: "An elite security fighter commissioned for system governors. Elegant lines hide an integrated antimatter reactor powering class-A laser optics.",
    velocidade: 84,
    aceleracao: 82,
    turbo: 84,
    energia: 45,
    massa: 25,
    price: 35000,
    abilityName: "Antimatter Pulse",
    abilityDesc: "Releases a localized wave that disables nearby enemy weapons and shield regenerators for 5 seconds."
  },
  {
    id: "sparrow-11",
    name: "Storm Herald",
    modelFile: "/StarSparrow11.glb",
    class: "Bomber",
    description: "A heavy-ordnance delivery craft designed to level ground batteries and crack open orbital defensive lines with seismic torpedoes.",
    velocidade: 58,
    aceleracao: 50,
    turbo: 68,
    energia: 65,
    massa: 60,
    price: 45000,
    abilityName: "Seismic Bombard",
    abilityDesc: "Drops a magnetic seismic charge that detonates with a massive gravity shockwave, crushing structures."
  },
  {
    id: "sparrow-12",
    name: "Phoenix Eclipse",
    modelFile: "/StarSparrow12.glb",
    class: "Heavy Fighter",
    description: "Featuring cutting-edge self-repairing nanite hulls, the Phoenix excels at war-of-attrition battles where other crafts fall apart.",
    velocidade: 82,
    aceleracao: 74,
    turbo: 92,
    energia: 40,
    massa: 40,
    price: 56000,
    abilityName: "Nanite Rebirth",
    abilityDesc: "Initiates a rapid hull-welding sequence that restores 50% of the maximum armor over 4 seconds."
  },
  {
    id: "sparrow-13",
    name: "Void Spectre",
    modelFile: "/StarSparrow13.glb",
    class: "Interceptor",
    description: "Built with materials harvested from the horizon of a collapsed star. It slides through space almost completely silent, leaving only a trace of Cherenkov radiation.",
    velocidade: 98,
    aceleracao: 94,
    turbo: 96,
    energia: 44,
    massa: 15,
    price: 68000,
    abilityName: "Void Slide",
    abilityDesc: "Fades into a dimensional pocket, allowing the ship to pass directly through physical obstacles."
  },
  {
    id: "sparrow-14",
    name: "Ragnarok Hammer",
    modelFile: "/StarSparrow14.glb",
    class: "Bomber",
    description: "Named after the ancient Norse end of worlds, this heavy bomber is fitted with a central siege laser capable of punching through flagship core shielding.",
    velocidade: 52,
    aceleracao: 45,
    turbo: 65,
    energia: 70,
    massa: 60,
    price: 82000,
    abilityName: "Siege Beam",
    abilityDesc: "Chunnels energy into a massive front-facing thermal ray, dealing astronomical damage over 3 seconds."
  },
  {
    id: "sparrow-15",
    name: "Apex Falcon",
    modelFile: "/StarSparrow15.glb",
    class: "Recon",
    description: "A high-altitude, long-endurance cruiser designed to scout uncharted deep-space anomalies. Includes an AI co-pilot module.",
    velocidade: 94,
    aceleracao: 99,
    turbo: 87,
    energia: 47,
    massa: 10,
    price: 98000,
    abilityName: "AI Co-pilot",
    abilityDesc: "Launches automated point-defense turrets that automatically target and destroy incoming missiles."
  },
  {
    id: "sparrow-16",
    name: "Star Sparrow XVI",
    modelFile: "/StarSparrow16.glb",
    class: "Corvette",
    description: "Part of the next-generation heavy Corvette series. Features multi-vectored thruster arrays and secondary plasma batteries for 360-degree combat coverage.",
    velocidade: 76,
    aceleracao: 65,
    turbo: 78,
    energia: 60,
    massa: 80,
    price: 115000,
    abilityName: "Plasma Flurry",
    abilityDesc: "Fires a rapid succession of seeking plasma charges that lock onto up to three targets simultaneously."
  },
  {
    id: "sparrow-17",
    name: "Star Sparrow XVII",
    modelFile: "/StarSparrow17.glb",
    class: "Corvette",
    description: "An upgrade to the Corvette chassis, incorporating heavy shield generators and a custom reactor core built to sustain long interstellar blockade missions.",
    velocidade: 78,
    aceleracao: 67,
    turbo: 80,
    energia: 62,
    massa: 80,
    price: 135000,
    abilityName: "Shield Overcharge",
    abilityDesc: "Forces the shields into an overcharged state, instantly restoring full shields and raising capacity by 50%."
  },
  {
    id: "sparrow-18",
    name: "Star Sparrow XVIII",
    modelFile: "/StarSparrow18.glb",
    class: "Dreadnought",
    description: "The peak of offensive starship engineering. A flying fortress equipped with side-mounted railgun rows and central antimatter missile silos.",
    velocidade: 48,
    aceleracao: 40,
    turbo: 58,
    energia: 82,
    massa: 120,
    price: 165000,
    abilityName: "Antimatter Missile",
    abilityDesc: "Launches a tracking missile that triggers an intense annihilation explosion, neutralizing shield bubbles."
  },
  {
    id: "sparrow-19",
    name: "Star Sparrow XIX",
    modelFile: "/StarSparrow19.glb",
    class: "Dreadnought",
    description: "An unmatched juggernaut ship. Utilizing heavy hyper-dense alloys, it can shrug off direct hits from planetary planetary cannons with ease.",
    velocidade: 50,
    aceleracao: 42,
    turbo: 60,
    energia: 85,
    massa: 120,
    price: 200000,
    abilityName: "Alloy Hardening",
    abilityDesc: "Hardens the outer hull plates, reducing all incoming hull damage by 80% for 10 seconds."
  },
  {
    id: "sparrow-20",
    name: "Star Sparrow XX",
    modelFile: "/StarSparrow20.glb",
    class: "Dreadnought",
    description: "The absolute pinnacle of deep space military dominance. The Star Sparrow XX stands as a marvel of engineering, merging extreme weapon grids with total defense barriers.",
    velocidade: 55,
    aceleracao: 46,
    turbo: 65,
    energia: 88,
    massa: 120,
    price: 250000,
    abilityName: "Nova Overload",
    abilityDesc: "Vents hyper-energy from the core, releasing a circular blast wave that vaporizes small craft and disables capital systems."
  }
];


export const SKINS_DATA: SkinData[] = [
  {
    id: "orange-alloy",
    name: "Ignição de Plasma",
    textureFile: "/StarSparrow_Orange.webp",
    colorHex: "#f97316",
    description: "O clássico liga tática de alta visibilidade usado em corridas solares."
  },
  {
    id: "red-core",
    name: "Núcleo Estelar",
    textureFile: "/StarSparrow_Red.webp",
    colorHex: "#ef4444",
    description: "Inspirado no calor intenso de uma estrela jovem em fusão."
  },
  {
    id: "blue-vortex",
    name: "Vórtice Quântico",
    textureFile: "/StarSparrow_Blue.webp",
    colorHex: "#3b82f6",
    description: "Uma pintura eletromagnética que flutua como energia quântica pura."
  },
  {
    id: "green-gamma",
    name: "Radiação Gamma",
    textureFile: "/StarSparrow_Green.webp",
    colorHex: "#10b981",
    description: "Um brilho esmeralda radioativo que intimida qualquer oponente no vácuo."
  },
  {
    id: "yellow-sun",
    name: "Singularidade Solar",
    textureFile: "/StarSparrow_Yellow.webp",
    colorHex: "#eab308",
    description: "Reflexos dourados polidos que capturam e amplificam a luz de sistemas binários."
  },
  {
    id: "purple-nebula",
    name: "Nébula de Antimatéria",
    textureFile: "/StarSparrow_Purple.webp",
    colorHex: "#a855f7",
    description: "Cores profundas e misteriosas colhidas do coração das nebulosas mais distantes."
  },
  {
    id: "cyan-ion",
    name: "Feixe de Íons",
    textureFile: "/StarSparrow_Cyan.webp",
    colorHex: "#06b6d4",
    description: "Revestimento experimental de íons para máxima eficiência em manobras rápidas."
  },
  {
    id: "grey-carbonite",
    name: "Liga de Carbonita",
    textureFile: "/StarSparrow_Grey.webp",
    colorHex: "#6b7280",
    description: "Metal bruto e resistente, forjado para suportar impactos em cinturões de asteroides."
  },
  {
    id: "black-vacuum",
    name: "Vácuo Absoluto",
    textureFile: "/StarSparrow_Black.webp",
    colorHex: "#18181b",
    description: "Nanotecnologia que absorve 99% da luz visível para operações furtivas de elite."
  },
  {
    id: "white-neutron",
    name: "Estrela de Nêutrons",
    textureFile: "/StarSparrow_White.webp",
    colorHex: "#fafafa",
    description: "Brilho intenso e pureza absoluta."
  },
  {
    id: "cammo-military",
    name: "Camuflado Militar",
    textureFile: "/StarSparrow_Special.webp",
    colorHex: "#4a5d23",
    description: "Padrão tático de camuflagem projetado para infiltração em campos de destroços."
  },
  {
    id: "earth-harmony",
    name: "Planeta Terra",
    textureFile: "/StarSparrow_Earth.webp",
    colorHex: "#0ea5e9",
    description: "Inspirada na beleza azul e verde do nosso planeta de origem, a Terra."
  }
];

export interface ClassProfile {
  name: string;
  focus: string;
  advantage: string;
  disadvantage: string;
}

export const SHIP_CLASS_PROFILES: Record<string, ClassProfile> = {
  Interceptor: {
    name: "Interceptor (Interceptadora)",
    focus: "Velocidade & Aceleração Extrema",
    advantage: "Aceleração instantânea e massa levíssima para manobras rápidas.",
    disadvantage: "Blindagem e escudos reduzidos devido ao chassi ultraleve."
  },
  Recon: {
    name: "Recon (Exploradora)",
    focus: "Mobilidade Ágil & Varredura",
    advantage: "Altíssima agilidade com excelente taxa de recarga dos motores.",
    disadvantage: "Poder de fogo reduzido focado em evasão e furtividade."
  },
  Fighter: {
    name: "Fighter (Caça de Combate)",
    focus: "Equilíbrio de Atributos",
    advantage: "Desempenho balanceado em combate, velocidade e blindagem.",
    disadvantage: "Não possui nenhuma especialização extrema nos sistemas."
  },
  "Heavy Fighter": {
    name: "Heavy Fighter (Caça Pesado)",
    focus: "Ataque Frontal & Blindagem",
    advantage: "Alta resistência e canhões de plasma pesados.",
    disadvantage: "Inércia perceptível nas curvas e velocidade de cruzeiro menor."
  },
  Bomber: {
    name: "Bomber (Bombardeira)",
    focus: "Demolição & Destruição",
    advantage: "Poder destrutivo massivo com mísseis e cargas sísmicas.",
    disadvantage: "Massa muito alta, manobras lentas e baixa agilidade."
  },
  Corvette: {
    name: "Corvette (Corveta Escolta)",
    focus: "Duração de Turbo & Energia",
    advantage: "Turbo Boost de longa duração e geradores de escudos robustos.",
    disadvantage: "Frenagem lenta e grande arrasto inercial de massa."
  },
  Dreadnought: {
    name: "Dreadnought (Couraçado)",
    focus: "Energia Máxima & Escudos",
    advantage: "Geradores de energia de fusão massivos com recarga rápida de turbo.",
    disadvantage: "Massa extrema, curva inercial difícil e velocidade base reduzida."
  }
};

export function calculateShipStats(ship: ShipData) {
  return {
    maxVelocity: ship.velocidade,
    acceleration: ship.aceleracao,
    turbo: ship.turbo,
    energy: ship.energia,
    mass: ship.massa
  };
}
