import { ShipData, SkinData, RouteData } from "./types";
import { playerService } from "./services/playerService";

export const ROUTES_DATA: RouteData[] = [
  {
    id: "route-certification",
    name: "Vôo de Certificação",
    description: "Um tutorial prático com 10 aros. Começa super fácil com aros alinhados e sem obstáculos, ficando um pouco desafiador com curvas e asteroides no fim.",
    image: "/route_certification.webp",
    numRings: 10,
    ringSpacing: 4000,
    curveIntensityX: 150,
    curveIntensityY: 100,
    curveFrequencyX: 0.2,
    curveFrequencyY: 0.1,
    randomOffset: 40,
    nebulaCount: 30,
    asteroidDensity: 1.2,
    asteroidVelocity: 0,
    difficulty: "Iniciante",
    totalDistance: 40000,
    ambientColor: "#0f172a",
    hasMovingAsteroids: false,
    trafficShipCount: 0,
    requiredLevel: 1
  },
  {
    id: "route-asteroid-alpha",
    name: "Cinturão de Asteroides Alpha",
    description: "Navegue pelo setor de testes cercado por asteroides flutuantes e luas. Perfeito para calibragem de propulsores.",
    image: "/route_asteroid_belt.webp",
    numRings: 12,
    ringSpacing: 4000,
    curveIntensityX: 250,
    curveIntensityY: 150,
    curveFrequencyX: 0.25,
    curveFrequencyY: 0.15,
    randomOffset: 80,
    nebulaCount: 20,
    asteroidDensity: 2.5,
    asteroidVelocity: 0,
    difficulty: "Iniciante",
    totalDistance: 48000,
    ambientColor: "#f97316",
    hasMovingAsteroids: false,
    trafficShipCount: 2,
    requiredLevel: 1
  },
  {
    id: "route-highway",
    name: "Via Láctea Expressa",
    description: "Uma rodovia interestelar de alta velocidade. Baixa densidade de obstáculos, mas distância extrema.",
    image: "/route_cosmic_highway.webp",
    numRings: 20,
    ringSpacing: 8000,
    curveIntensityX: 80,
    curveIntensityY: 80,
    curveFrequencyX: 0.02,
    curveFrequencyY: 0.02,
    randomOffset: 20,
    nebulaCount: 60,
    asteroidDensity: 0.2,
    asteroidVelocity: 0,
    difficulty: "Fácil",
    totalDistance: 160000,
    ambientColor: "#10b981",
    hasMovingAsteroids: false,
    trafficShipCount: 40,
    requiredLevel: 2
  },
  {
    id: "route-orion-nebula",
    name: "Vórtice da Nebulosa de Órion",
    description: "Uma corrida tática através de um labirinto instável de gás superaquecido e poeira cósmica ionizada.",
    image: "/route_orion_nebula.webp",
    numRings: 15,
    ringSpacing: 3800,
    curveIntensityX: 550,
    curveIntensityY: 350,
    curveFrequencyX: 0.55,
    curveFrequencyY: 0.45,
    randomOffset: 250,
    nebulaCount: 150,
    asteroidDensity: 0.8,
    asteroidVelocity: 8,
    difficulty: "Médio",
    totalDistance: 57000,
    ambientColor: "#a855f7",
    hasMovingAsteroids: true,
    trafficShipCount: 5,
    requiredLevel: 3
  },
  {
    id: "route-ice-field",
    name: "Campos Glaciais de Europa",
    description: "Navegue por um oceano congelado suspenso no espaço. Milhares de blocos de gelo estáticos bloqueiam o caminho.",
    image: "/route_ice_field.webp",
    numRings: 16,
    ringSpacing: 4200,
    curveIntensityX: 250,
    curveIntensityY: 250,
    curveFrequencyX: 0.2,
    curveFrequencyY: 0.2,
    randomOffset: 120,
    nebulaCount: 15,
    asteroidDensity: 12.0,
    asteroidVelocity: 0,
    difficulty: "Médio",
    totalDistance: 67200,
    ambientColor: "#0c4a6e",
    hasMovingAsteroids: false,
    trafficShipCount: 2,
    requiredLevel: 4
  },
  {
    id: "route-void",
    name: "Silêncio do Vazio",
    description: "Um teste de velocidade pura e controle inercial. Sem obstáculos, apenas o vácuo absoluto e curvas extremas.",
    image: "/route_void_silence.webp",
    numRings: 20,
    ringSpacing: 6000,
    curveIntensityX: 1800,
    curveIntensityY: 1800,
    curveFrequencyX: 0.18,
    curveFrequencyY: 0.15,
    randomOffset: 1200,
    nebulaCount: 0,
    asteroidDensity: 0,
    asteroidVelocity: 0,
    difficulty: "Médio",
    totalDistance: 120000,
    ambientColor: "#09090b",
    hasMovingAsteroids: false,
    trafficShipCount: 0,
    requiredLevel: 5
  },
  {
    id: "route-saturn-rings",
    name: "Anéis Táticos de Saturno",
    description: "Circuito de precisão máxima situado nas fendas geladas dos icônicos anéis planetários de Saturno.",
    image: "/route_saturn_rings.webp",
    numRings: 20,
    ringSpacing: 4500,
    curveIntensityX: 400,
    curveIntensityY: 150,
    curveFrequencyX: 0.2,
    curveFrequencyY: 0.1,
    randomOffset: 100,
    nebulaCount: 10,
    asteroidDensity: 8.0,
    asteroidVelocity: 0,
    difficulty: "Difícil",
    totalDistance: 90000,
    ambientColor: "#3b82f6",
    hasMovingAsteroids: false,
    trafficShipCount: 3,
    requiredLevel: 6
  },
  {
    id: "route-plasma",
    name: "Tormenta Energética",
    description: "Relâmpagos cósmicos e nuvens de plasma ionizado. A visibilidade é baixa e as curvas são fechadas.",
    image: "/route_plasma_storm.webp",
    numRings: 16,
    ringSpacing: 3600,
    curveIntensityX: 800,
    curveIntensityY: 800,
    curveFrequencyX: 1.2,
    curveFrequencyY: 1.0,
    randomOffset: 650,
    nebulaCount: 100,
    asteroidDensity: 1.5,
    asteroidVelocity: 30,
    difficulty: "Difícil",
    totalDistance: 57600,
    ambientColor: "#8b5cf6",
    hasMovingAsteroids: true,
    trafficShipCount: 4,
    requiredLevel: 7
  },
  {
    id: "route-supernova",
    name: "Remanescente de Supernova",
    description: "Voe através dos restos incandescentes de uma estrela morta, onde detritos em chamas voam em todas as direções.",
    image: "/route_supernova.webp",
    numRings: 15,
    ringSpacing: 3200,
    curveIntensityX: 850,
    curveIntensityY: 850,
    curveFrequencyX: 0.8,
    curveFrequencyY: 0.8,
    randomOffset: 600,
    nebulaCount: 80,
    asteroidDensity: 4.5,
    asteroidVelocity: 45,
    difficulty: "Elite",
    totalDistance: 48000,
    ambientColor: "#ef4444",
    hasMovingAsteroids: true,
    trafficShipCount: 0,
    requiredLevel: 8
  },
  {
    id: "route-black-hole",
    name: "Horizonte de Eventos",
    description: "A gravidade distorce o espaço-tempo. Curvas impossíveis e uma força invisível puxam sua nave para o abismo.",
    image: "/route_black_hole.webp",
    numRings: 18,
    ringSpacing: 3500,
    curveIntensityX: 1200,
    curveIntensityY: 1200,
    curveFrequencyX: 0.05,
    curveFrequencyY: 0.05,
    randomOffset: 600,
    nebulaCount: 40,
    asteroidDensity: 0.5,
    asteroidVelocity: 80,
    difficulty: "Elite",
    totalDistance: 63000,
    ambientColor: "#1e1b4b",
    hasMovingAsteroids: true,
    trafficShipCount: 1,
    gravityWell: true,
    requiredLevel: 9
  },
  {
    id: "route-dyson",
    name: "Sucata de Dyson",
    description: "Os restos de uma megaestrutura antiga. Destroços metálicos densos tornam a navegação um pesadelo de sobrevivência.",
    image: "/route_dyson_scraps.webp",
    numRings: 20,
    ringSpacing: 2800,
    curveIntensityX: 300,
    curveIntensityY: 300,
    curveFrequencyX: 0.3,
    curveFrequencyY: 0.3,
    randomOffset: 350,
    nebulaCount: 5,
    asteroidDensity: 15.0,
    asteroidVelocity: 15,
    difficulty: "Sobrevivência",
    totalDistance: 56000,
    ambientColor: "#71717a",
    hasMovingAsteroids: true,
    trafficShipCount: 0,
    requiredLevel: 10
  }
];

export const SHIPS_DATA: ShipData[] = [
  {
    id: "sparrow-01",
    name: "Sparrow",
    modelFile: "/NaveJogador.glb",
    class: "Interceptor",
    description: "Primeiro modelo operacional da série Wing. Leve, simples e extremamente fácil de controlar, ideal para pilotos iniciantes.",
    velocidade: 4,
    aceleracao: 3,
    turbo: 3,
    energia: 1,
    massa: 2,
    price: 0,
    abilityName: "Overdrive Boost",
    abilityDesc: "Aumenta temporariamente a velocidade e concata propulsão quântica.",
    requiredLevel: 1
  },
  {
    id: "sparrow-02",
    name: "Kestrel",
    modelFile: "/StarSparrow02.glb",
    class: "Recon",
    description: "Versão de treinamento equipada com propulsores experimentais. Compensa sua baixa potência com excelente capacidade de turbo.",
    velocidade: 3,
    aceleracao: 2,
    turbo: 4,
    energia: 1,
    massa: 2,
    price: 2500,
    abilityName: "Sensor Sweep",
    abilityDesc: "Mapeia anomalias à frente destacando a trajetória ideal.",
    requiredLevel: 1
  },
  {
    id: "sparrow-03",
    name: "Falcon",
    modelFile: "/StarSparrow03.glb",
    class: "Fighter",
    description: "Primeiro caça de reconhecimento da corporação. Rápido e equilibrado para missões de exploração.",
    velocidade: 5,
    aceleracao: 3,
    turbo: 3,
    energia: 2,
    massa: 2,
    price: 4500,
    abilityName: "Cloak Field",
    abilityDesc: "Gera camuflagem óptica temporária reduzindo arrasto.",
    requiredLevel: 2
  },
  {
    id: "sparrow-04",
    name: "Bulwark",
    modelFile: "/StarSparrow04.glb",
    class: "Heavy Fighter",
    description: "Projeto pesado destinado a atravessar campos de destroços e suportar impactos extremos.",
    velocidade: 2,
    aceleracao: 2,
    turbo: 2,
    energia: 4,
    massa: 5,
    price: 6000,
    abilityName: "Reflector Shield",
    abilityDesc: "Fortalece os escudos absorvendo impacto de asteroides.",
    requiredLevel: 2
  },
  {
    id: "sparrow-05",
    name: "Viper",
    modelFile: "/StarSparrow20.glb",
    class: "Interceptor",
    description: "Caça interceptor desenvolvido para perseguições de alta velocidade e mudanças bruscas de direção.",
    velocidade: 5,
    aceleracao: 5,
    turbo: 4,
    energia: 2,
    massa: 2,
    price: 9500,
    abilityName: "Plasma Burst",
    abilityDesc: "Injeta plasma nos motores para impulso imediato.",
    requiredLevel: 3
  },
  {
    id: "sparrow-06",
    name: "Sentinel",
    modelFile: "/StarSparrow06.glb",
    class: "Corvette",
    description: "Modelo de patrulha espacial criado para missões prolongadas e proteção de rotas comerciais.",
    velocidade: 3,
    aceleracao: 3,
    turbo: 3,
    energia: 4,
    massa: 5,
    price: 13000,
    abilityName: "Aegis Barrier",
    abilityDesc: "Cria barreira de proteção de alta densidade.",
    requiredLevel: 3
  },
  {
    id: "sparrow-07",
    name: "Ghost",
    modelFile: "/StarSparrow07.glb",
    class: "Recon",
    description: "Protótipo furtivo de baixa assinatura térmica, extremamente ágil e difícil de rastrear.",
    velocidade: 6,
    aceleracao: 5,
    turbo: 5,
    energia: 3,
    massa: 2,
    price: 17500,
    abilityName: "Decoy Spark",
    abilityDesc: "Lança feixe de ions dispersando obstáculos.",
    requiredLevel: 4
  },
  {
    id: "sparrow-08",
    name: "Bastion",
    modelFile: "/StarSparrow08.glb",
    class: "Heavy Fighter",
    description: "Fortaleza móvel construída para sobreviver onde nenhuma outra nave conseguiria.",
    velocidade: 3,
    aceleracao: 3,
    turbo: 2,
    energia: 6,
    massa: 7,
    price: 22000,
    abilityName: "Fortress Wall",
    abilityDesc: "Ativa os geradores de reserva para reabastecimento de energia.",
    requiredLevel: 4
  },
  {
    id: "sparrow-09",
    name: "Nova",
    modelFile: "/StarSparrow09.glb",
    class: "Interceptor",
    description: "Projeto de segunda geração que combina potência, estabilidade e excelente autonomia energética.",
    velocidade: 6,
    aceleracao: 5,
    turbo: 4,
    energia: 5,
    massa: 4,
    price: 28000,
    abilityName: "Nova Drive",
    abilityDesc: "Libera carga de fusão para aceleração contínua.",
    requiredLevel: 5
  },
  {
    id: "sparrow-10",
    name: "Phantom",
    modelFile: "/StarSparrow10.glb",
    class: "Fighter",
    description: "Caça de infiltração extremamente veloz, desenvolvido para atravessar territórios hostis sem ser detectado.",
    velocidade: 7,
    aceleracao: 6,
    turbo: 6,
    energia: 3,
    massa: 2,
    price: 35000,
    abilityName: "Phase Shift",
    abilityDesc: "Deslocamento quântico instantâneo desviando de perigos.",
    requiredLevel: 5
  },
  {
    id: "sparrow-11",
    name: "Titan",
    modelFile: "/StarSparrow11.glb",
    class: "Bomber",
    description: "Colosso espacial equipado com enormes reservas de energia e blindagem reforçada.",
    velocidade: 4,
    aceleracao: 4,
    turbo: 3,
    energia: 8,
    massa: 8,
    price: 45000,
    abilityName: "Titan Shield",
    abilityDesc: "Eleva os campos de força ao nível máximo.",
    requiredLevel: 6
  },
  {
    id: "sparrow-12",
    name: "Eclipse",
    modelFile: "/StarSparrow12.glb",
    class: "Heavy Fighter",
    description: "Modelo avançado projetado para operações em regiões de baixa luminosidade e tempestades cósmicas.",
    velocidade: 7,
    aceleracao: 6,
    turbo: 5,
    energia: 5,
    massa: 4,
    price: 56000,
    abilityName: "Eclipse Surge",
    abilityDesc: "Surtos elétricos aumentam a resposta do motor.",
    requiredLevel: 6
  },
  {
    id: "sparrow-13",
    name: "Comet",
    modelFile: "/StarSparrow13.glb",
    class: "Interceptor",
    description: "Construída para velocidade absoluta, sua aceleração lembra um cometa cruzando o vazio.",
    velocidade: 8,
    aceleracao: 7,
    turbo: 6,
    energia: 5,
    massa: 4,
    price: 68000,
    abilityName: "Comet Tail",
    abilityDesc: "Deixa um rastro de energia que estabiliza o voo.",
    requiredLevel: 7
  },
  {
    id: "sparrow-14",
    name: "Guardian",
    modelFile: "/StarSparrow14.glb",
    class: "Bomber",
    description: "Última linha de defesa das colônias humanas. Quase indestrutível em combate direto.",
    velocidade: 4,
    aceleracao: 4,
    turbo: 4,
    energia: 9,
    massa: 9,
    price: 82000,
    abilityName: "Guardian Aura",
    abilityDesc: "Aura protetora permanente que absorve choques.",
    requiredLevel: 7
  },
  {
    id: "sparrow-15",
    name: "Specter",
    modelFile: "/StarSparrow15.glb",
    class: "Recon",
    description: "Uma evolução do Ghost, capaz de combinar velocidade extrema com grande eficiência energética.",
    velocidade: 8,
    aceleracao: 8,
    turbo: 7,
    energia: 6,
    massa: 4,
    price: 98000,
    abilityName: "Hyper Drive",
    abilityDesc: "Propulsão hiperespacial de emergência.",
    requiredLevel: 8
  },
  {
    id: "sparrow-16",
    name: "Leviathan",
    modelFile: "/StarSparrow16.glb",
    class: "Corvette",
    description: "A maior nave já produzida pela corporação. Seu tamanho impressiona tanto quanto sua resistência.",
    velocidade: 5,
    aceleracao: 4,
    turbo: 4,
    energia: 10,
    massa: 10,
    price: 115000,
    abilityName: "Leviathan Core",
    abilityDesc: "Regenera escudos e energia continuamente.",
    requiredLevel: 8
  },
  {
    id: "sparrow-17",
    name: "Horizon",
    modelFile: "/StarSparrow17.glb",
    class: "Corvette",
    description: "Desenvolvida para viagens interplanetárias de longa distância, mantendo alto desempenho em qualquer ambiente.",
    velocidade: 8,
    aceleracao: 8,
    turbo: 7,
    energia: 7,
    massa: 6,
    price: 135000,
    abilityName: "Horizon Pulse",
    abilityDesc: "Onda infravermelha estabilizadora de direção.",
    requiredLevel: 9
  },
  {
    id: "sparrow-18",
    name: "Tempest",
    modelFile: "/StarSparrow18.glb",
    class: "Interceptor",
    description: "Especialista em atravessar anomalias gravitacionais e tempestades espaciais em velocidades extremas.",
    velocidade: 9,
    aceleracao: 8,
    turbo: 8,
    energia: 6,
    massa: 5,
    price: 165000,
    abilityName: "Tempest Engine",
    abilityDesc: "Combustão em cadeia para altíssima velocidade.",
    requiredLevel: 9
  },
  {
    id: "sparrow-19",
    name: "Solaris",
    modelFile: "/StarSparrow19.glb",
    class: "Dreadnought",
    description: "O ápice da engenharia convencional. Alimentada por um núcleo estelar miniaturizado, representa tudo o que a humanidade acreditava ser possível.",
    velocidade: 9,
    aceleracao: 8,
    turbo: 8,
    energia: 8,
    massa: 7,
    price: 200000,
    abilityName: "Solar Flare",
    abilityDesc: "Explosão de energia fotônica para velocidade máxima.",
    requiredLevel: 10
  },
  {
    id: "sparrow-20",
    name: "Prototype Wing",
    modelFile: "/StarSparrow05.glb",
    class: "Dreadnought",
    description: "Registro confidencial. O primeiro protótipo do Projeto Wing, ocultado por décadas. Seus sistemas permanecem perfeitamente equilibrados e seu verdadeiro propósito só é revelado aos pilotos capazes de completar o ciclo.",
    velocidade: 8,
    aceleracao: 8,
    turbo: 8,
    energia: 8,
    massa: 8,
    price: 250000,
    abilityName: "Proto Core",
    abilityDesc: "Ativa todos os sistemas protótipos na capacidade máxima.",
    requiredLevel: 10
  }
];


export const SKINS_DATA: SkinData[] = [
  {
    id: "orange-alloy",
    name: "Ignição de Plasma",
    textureFile: "/StarSparrow_Orange.webp",
    colorHex: "#f97316",
    description: "O clássico liga tática de alta visibilidade usado em corridas solares."
  },
  {
    id: "red-core",
    name: "Núcleo Estelar",
    textureFile: "/StarSparrow_Red.webp",
    colorHex: "#ef4444",
    description: "Inspirado no calor intenso de uma estrela jovem em fusão."
  },
  {
    id: "blue-vortex",
    name: "Vórtice Quântico",
    textureFile: "/StarSparrow_Blue.webp",
    colorHex: "#3b82f6",
    description: "Uma pintura eletromagnética que flutua como energia quântica pura."
  },
  {
    id: "green-gamma",
    name: "Radiação Gamma",
    textureFile: "/StarSparrow_Green.webp",
    colorHex: "#10b981",
    description: "Um brilho esmeralda radioativo que intimida qualquer oponente no vácuo."
  },
  {
    id: "yellow-sun",
    name: "Singularidade Solar",
    textureFile: "/StarSparrow_Yellow.webp",
    colorHex: "#eab308",
    description: "Reflexos dourados polidos que capturam e amplificam a luz de sistemas binários."
  },
  {
    id: "purple-nebula",
    name: "Nébula de Antimatéria",
    textureFile: "/StarSparrow_Purple.webp",
    colorHex: "#a855f7",
    description: "Cores profundas e misteriosas colhidas do coração das nebulosas mais distantes."
  },
  {
    id: "cyan-ion",
    name: "Feixe de Íons",
    textureFile: "/StarSparrow_Cyan.webp",
    colorHex: "#06b6d4",
    description: "Revestimento experimental de íons para máxima eficiência em manobras rápidas."
  },
  {
    id: "grey-carbonite",
    name: "Liga de Carbonita",
    textureFile: "/StarSparrow_Grey.webp",
    colorHex: "#6b7280",
    description: "Metal bruto e resistente, forjado para suportar impactos em cinturões de asteroides."
  },
  {
    id: "black-vacuum",
    name: "Vácuo Absoluto",
    textureFile: "/StarSparrow_Black.webp",
    colorHex: "#18181b",
    description: "Nanotecnologia que absorve 99% da luz visível para operações furtivas de elite."
  },
  {
    id: "white-neutron",
    name: "Estrela de Nêutrons",
    textureFile: "/StarSparrow_White.webp",
    colorHex: "#fafafa",
    description: "Brilho intenso e pureza absoluta."
  },
  {
    id: "cammo-military",
    name: "Camuflado Militar",
    textureFile: "/StarSparrow_Special.webp",
    colorHex: "#4a5d23",
    description: "Padrão tático de camuflagem projetado para infiltração em campos de destroços."
  },
  {
    id: "earth-harmony",
    name: "Planeta Terra",
    textureFile: "/StarSparrow_Earth.webp",
    colorHex: "#0ea5e9",
    description: "Inspirada na beleza azul e verde do nosso planeta de origem, a Terra."
  }
];

export interface ClassProfile {
  name: string;
  focus: string;
  advantage: string;
  disadvantage: string;
}

export const SHIP_CLASS_PROFILES: Record<string, ClassProfile> = {
  Interceptor: {
    name: "Interceptor (Interceptadora)",
    focus: "Velocidade & Aceleração Extrema",
    advantage: "Aceleração instantânea e massa levíssima para manobras rápidas.",
    disadvantage: "Blindagem e escudos reduzidos devido ao chassi ultraleve."
  },
  Recon: {
    name: "Recon (Exploradora)",
    focus: "Mobilidade Ágil & Varredura",
    advantage: "Altíssima agilidade com excelente taxa de recarga dos motores.",
    disadvantage: "Poder de fogo reduzido focado em evasão e furtividade."
  },
  Fighter: {
    name: "Fighter (Caça de Combate)",
    focus: "Equilíbrio de Atributos",
    advantage: "Desempenho balanceado em combate, velocidade e blindagem.",
    disadvantage: "Não possui nenhuma especialização extrema nos sistemas."
  },
  "Heavy Fighter": {
    name: "Heavy Fighter (Caça Pesado)",
    focus: "Ataque Frontal & Blindagem",
    advantage: "Alta resistência e canhões de plasma pesados.",
    disadvantage: "Inércia perceptível nas curvas e velocidade de cruzeiro menor."
  },
  Bomber: {
    name: "Bomber (Bombardeira)",
    focus: "Demolição & Destruição",
    advantage: "Poder destrutivo massivo com mísseis e cargas sísmicas.",
    disadvantage: "Massa muito alta, manobras lentas e baixa agilidade."
  },
  Corvette: {
    name: "Corvette (Corveta Escolta)",
    focus: "Duração de Turbo & Energia",
    advantage: "Turbo Boost de longa duração e geradores de escudos robustos.",
    disadvantage: "Frenagem lenta e grande arrasto inercial de massa."
  },
  Dreadnought: {
    name: "Dreadnought (Couraçado)",
    focus: "Energia Máxima & Escudos",
    advantage: "Geradores de energia de fusão massivos com recarga rápida de turbo.",
    disadvantage: "Massa extrema, curva inercial difícil e velocidade base reduzida."
  }
};

export function calculateShipStats(ship: ShipData) {
  const boost = playerService.getShipBoost(ship.id);
  const v = boost?.velocidade || 0;
  const a = boost?.aceleracao || 0;
  const t = boost?.turbo || 0;
  const e = boost?.energia || 0;
  const m = boost?.massa || 0;

  const vel = Math.min(10, ship.velocidade + v);
  const ace = Math.min(10, ship.aceleracao + a);
  const tur = Math.min(10, ship.turbo + t);
  const eng = Math.min(10, ship.energia + e);
  const mas = Math.min(10, ship.massa + m);

  return {
    vel,
    ace,
    tur,
    eng,
    mas,

    // Scaled to 0-100 range for simulator physics and UI bars
    maxVelocity: Math.min(100, Math.round((vel / 10) * 100)),
    acceleration: Math.min(100, Math.round((ace / 10) * 100)),
    turbo: Math.min(100, Math.round((tur / 10) * 100)),
    energy: Math.min(100, Math.round((eng / 10) * 100)),
    mass: Math.min(100, Math.round((mas / 10) * 100))
  };
}
